abhiTronix/vidgear

- README.md
In README.md, change
`pip install opencv-python-contrib`
to 
`pip install opencv-contrib-python`
> doc: opencv-python-contrib to opencv-contrib-python

- vidgear/gears/camgear.py
- vidgear/tests/benchmark_tests/test_benchmark_Videocapture.py
- vidgear/tests/benchmark_tests/test_benchmark_Videowriter.py
- vidgear/tests/benchmark_tests/test_benchmark_playback.py
- vidgear/tests/videocapture_tests/test_camgear.py
- vidgear/tests/videocapture_tests/test_videogear.py
This PR introduces **Threaded Queue Mode for CamGear Class(_works with VideoGear Common Class too_), that enables Blocking use of the source in Fixed-Length Video Streams.** This Mode is enabled by default for any Videocapture stream(_except any connected Camera/H.W devices_). 
To manually alter this mode, CamGear Class now provides **`THREADED_QUEUE_MODE`** user-defined flag. This flag can be easily set to `True`(_to enable_) or unset to `False`_(to disable_) this mode by passing this parameter to [`**options`](https://github.com/abhiTronix/vidgear/wiki/CamGear-Class#parameters-and-attributes-wrench) dict of CamGear class as follows:
```python
options = {'THREADED_QUEUE_MODE': False} #to disable Threaded Queue Mode
```
- Enables Blocking, Sequential and Threaded LIFO Frame Handling.
- It …
> Enhancement: Threaded Queue Mode for CamGear Class

- README.md
- vidgear/gears/camgear.py
- vidgear/gears/helper.py
- vidgear/gears/stabilizer.py
- vidgear/gears/videogear.py
- vidgear/tests/videocapture_tests/test_camgear.py
- vidgear/tests/videocapture_tests/test_videogear.py
This PR introduces  **Powerful Real-time Video Stabilizer for VidGear.** _This stabilizer can work both standalone and with VidGear Multi-Threaded Classes and thereby is solely integrated into vidgear's `VideoGear` Class._ **This `VideoGear` stabilizer for any given video stream can be activated anytime with `stabilize` boolean flag.**
#22 
- Real-time stabilization with low latency and no extra resources.
- Works exceptionally well with low-frequency jitter.
- Compatible with any vidgear's video streams including live network streams.
- Works both standalone and with VidGear Multi-Threaded Classes.
- Direct flexible integration into vidgear's `VideoGear` Class.
> Enhancement: Introducing Powerful Real-time Video Stabilizer for VidGear

- vidgear/gears/screengear.py
In fact, the old code was a copy of the `mss.mss()` factory.
Fixes #38.
This is a cleanup patch to prevent double work in case the OS is not handled. The new code is also more readable.
None.
> Remove duplicate code to import MSS

- .travis.yml
- appveyor.yml
- scripts/bash/prepare_dataset.sh
- vidgear/tests/benchmark_tests/test_benchmark_Videowriter.py
- vidgear/tests/benchmark_tests/test_benchmark_playback.py
- vidgear/tests/test_helper.py
- vidgear/tests/videocapture_tests/test_camgear.py
- vidgear/tests/writer_tests/test_compression_mode.py
- vidgear/tests/writer_tests/test_non_compression_mode.py
This PR is aimed at bringing OSX python-support to VidGear by implementing automated Travis CLI test environment similar to Linux and fixing the bugs encountered in the way.
**Noteworthy Changes:**
- Dropped Python 2.7 Support from CLI Tests
- Reformatted travis.yml from scratch
- Added native support for MacOS environment
- Added necessary system-specific dependencies
- Added Static binaries FFmpeg for MacOS
- Fixed Redundant URL
- Fixed Bugs
- Updated Docs
#41 
This proposal aims at bringing this OSX python-support to VidGear by implementing automated Travis CLI pytest similar to Linux environments and fixing the bugs encountered so that VidGear can work seamlessly on OSX systems too.
> [Enhancement] Adding OSX environment support for Travis Cli tests

- vidgear/gears/helper.py
- vidgear/gears/netgear.py
- vidgear/gears/screengear.py
_This PR introduces powerful, smart & secure ZeroMQ's Security Layers for NetGear API that enables strong encryption on data, and (_as far as we know_) unbreakable authentication between Servers and Client with the help of custom auth certificates/keys._ 
**This PR introduces supports for the two most powerful ZMQ security mechanisms:**
- **Stonehouse:** which switches to the _"CURVE"_ security mechanism, giving us strong encryption on data, and (as far as we know) unbreakable authentication. Stonehouse is the minimum you would use over public networks and assures clients that they are speaking to an authentic server while allowing any client to connect. **It is less secure but faster than IronHouse security mechanism.**
- **Ironhouse:** which extends Stonehouse with client public key …
> Enhancement: Introducing powerful ZMQ Authentication & Data Encryption features for NetGear API

- vidgear/gears/netgear.py
- vidgear/gears/pigear.py
This PR introduces Encoding/Decoding compression capabilities for NetGear API for optimizing performance while sending the frames of large size directly over the network by encoding the frame before sending it and decoding it on the client's end automatically all in real-time. To achieve this NetGear API utilizes OpenCV's `imencode` & `imdecode` functions in conjunction with its flexible APIs and robustly handles all errors
- added compression support with on-the-fly flexible frame encoding on the server-side
- added initial support for JPEG, PNG & BMP encoding formats 
- added exclusive options attribute `compression_format` & `compression_param` to tweak this feature
- client-side will now decode frame automatically based on the encoding as well as support decoding flags.
- Updated docs …
> Enhancement: Introducing real-time Encoding/Decoding for NetGear API

- vidgear/gears/helper.py
__self__ is an undefined name in this context which will raise NameError.
__logger__ defined on line 62.
#89 
__self__ is an undefined name in this context which will raise NameError.
None
> Undefined name: 'self'.  'logger' defined on line 62

- .travis.yml
**Add flake8 to travis to find undefined names:** https://flake8.pycqa.org/en/latest/user/error-codes.html
#92
On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead these tests are focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic language like Python they result in the script halting/crashing on the user.
* F63 tests are usually about the confusion between identity and equality in …
> Travis CI: Run flake8 to find undefined names

- changelog.md
- vidgear/gears/screengear.py
- vidgear/tests/benchmark_tests/test_benchmark_Videowriter.py
- vidgear/tests/videocapture_tests/test_camgear.py
This PR aims at fixing various undefined names errors within vidgear discovered by flake8 tests.
#92 
Vidgear recently added flake8 Tests for Travis CLI Linux environments in order to address various undefined name errors(PR #91) and thereby this PR aims at fixing them. 
None
> Fixes for flake8 Tests

- vidgear/gears/asyncio/netgear_async.py
The following issue arises when switching from legacy to async when using `address` and `port` as kwargs:
```
NetGear_Async :: ERROR :: 'NetGear_Async' object has no attribute '_NetGear_Async__address'
Traceback (most recent call last):
File "/home/christian/workspace/scarecrow/env/lib/python3.7/site-packages/vidgear/gears/asyncio/netgear_async.py", line 304, in __server_handler
self.__protocol + "://" + str(self.__address) + ":" + str(self.__port)
```
The code checks for whether the kwargs are None and defaults them, but never sets the passed arguments
https://github.com/abhiTronix/vidgear/issues/117
Otherwise, vidgear w/ async only works locally on the default port/address.
Before:
After:
>  __address and __port are not set in async mode 

- docs/gears/netgear/advanced/bidirectional_mode.md
- docs/gears/netgear/advanced/compression.md
- docs/gears/netgear/advanced/multi_client.md
- docs/gears/netgear/advanced/multi_server.md
- docs/gears/netgear/advanced/secure_mode.md
- docs/gears/netgear/params.md
- docs/gears/writegear/compression/params.md
- docs/gears/writegear/compression/usage.md
- vidgear/gears/helper.py
- vidgear/gears/netgear.py
- vidgear/gears/writegear.py
- vidgear/tests/network_tests/test_netgear.py
- vidgear/tests/test_helper.py
This PR add support for **`-clones`** list attribute, which sets the special FFmpeg arguments that are repeated more than once in the terminal command. User can now format repeating duplicate parameter as list and pass with this attribute of `output_param` dictionary parameter in WriteGear API.
- Added new `-clones` attribute in `output_params` parameter for handing this behavior.
- Implemented support to pass arguments as list for this attribute, and maintaining the exact order it was specified.
- Added new helper.py test for `dict2Args` function for debugging this behavior.
- Updated docs accordingly.
#141
This PR solves special case where FFmpeg arguments that are repeated more than once in the terminal command.
**Merging audio with video:**
```python
from vidgear.gears import …
```
> WriteGear API: Added support for adding duplicate arguments to `output_params` parameter (Fixes #141)

- vidgear/gears/camgear.py
Perform benchmark requested by @abhiTronix at https://github.com/abhiTronix/vidgear/pull/21 and also optimise the threaded queue implementation.  
* Replace regular queue.full checks followed by sleep with implicit sleep due to blocking queue.put
* Replace regular queue.empty checks followed by queue.nowait_get with a  blocking queue.get with implicit empty check
https://github.com/abhiTronix/vidgear/pull/21
We are working to improve the speed of this reader under i/o bound and cpu bound situations. 
```
git clone https://github.com/abhiTronix/vidgear.git && cd vidgear
git checkout development
pip install .
```
Was used to run:
https://github.com/bml1g12/benchmarking_video_reading_python/blob/d42ac5769334378d52bfbfcb607161847dd20f7a/video_reading_benchmarks/benchmarks.py#L235
Which is …
> feat(camgear): optimise threaded queue implementation speed

- .github/workflows/ci_linux.yml
- appveyor.yml
- azure-pipelines.yml
- setup.py
- vidgear/gears/asyncio/webgear_rtc.py
- vidgear/gears/netgear.py
- vidgear/tests/streamer_tests/asyncio_tests/test_webgear_rtc.py
Fixes Video-Frames Transfer in Bidirectional Mode and also Multi-Clients Mode is broken when frame compression is enabled.
#226
This PR fixes critical bug in NetGear that results in errors or no Bidirectional Video-Frame transfer when frame compression is enabled. The bug was originally reported here: https://stackoverflow.com/questions/68049432/vidgear-bidirectional-mode-gives-errors
> NetGear: Fixed Bidirectional Video-Frame Transfer broken with frame compression

- azure-pipelines.yml
- docs/gears/netgear/advanced/compression.md
- docs/gears/netgear/params.md
- mkdocs.yml
- vidgear/gears/asyncio/__main__.py
- vidgear/gears/netgear.py
- vidgear/tests/network_tests/test_netgear.py
- vidgear/tests/streamer_tests/asyncio_tests/test_webgear_rtc.py
NetGear currently only supports `BGR` colorspace frames as input with its [Frame Compression](https://abhitronix.github.io/vidgear/v0.2.2-dev/gears/netgear/advanced/compression/) but rejects any other colorspaces(always defaults to `BGR`). This PR will add support for additional colorspaces that can be specified manually.
#230 
NetGear API currently only supports `BGR` colorspace and also doesn't let users to manually alter it when its Frame Compression mode is enabled. But under the hood, backend `simplejpeg` library do support specifying input frames colorspace with its `encode_jpeg` and `decode_jpeg` methods. Thereby, This PR will track merge of this update that allow users to directly control input frames colorspace. 
None
> ✨ NetGear: New additional colorspace frames support to Frame Compression

- docs/gears/webgear_rtc/advanced.md
- docs/gears/webgear_rtc/params.md
- docs/help/netgear_ex.md
- docs/help/screengear_ex.md
- docs/help/webgear_rtc_ex.md
- docs/overrides/main.html
- mkdocs.yml
- vidgear/gears/asyncio/webgear_rtc.py
- vidgear/tests/streamer_tests/asyncio_tests/test_webgear_rtc.py
- vidgear/tests/videocapture_tests/test_camgear.py
With this PR, WebGear_RTC now provides `custom_stream` attribute with its `options` parameter that allows you to easily define your own Custom Streaming Class with suitable source that you want to use to transform your frames before sending them onto the browser. This implementation support Auto-Reconnection or Auto-Refresh works out-of-the-box.
- 💥 Removed support for assigning Custom Media Server Class(inherited from aiortc's VideoStreamTrack) in WebGear_RTC through its `config` global parameter.
- ✨ Added new `custom_stream` attribute with WebGear_RTC `options` parameter that allows you to easily define your own Custom Streaming Class with suitable source(such as OpenCV).
- ⚡️ This implementation supports repeated Auto-Reconnection or Auto-Refresh out-of-the-box.
- 🧑‍💻 This …
> ⚡️ WebGear_RTC: Implemented a new easy way of defining Custom Streaming Class

- vidgear/gears/streamgear.py
I'm sorry for committing to master branch.
I committed to testing branch again.
Fixed hls_segmet_type option not working bug in StreamGear
Fixed logging option not working bug in StreamGear
- hls_segment_type option
I changed the hls_segment_type option to 'fmp4', but it doesn't work.
The reason is that hls_segment_type is a 'str' type, but it is checked as 'int', so it is always set to the default type 'mpegts'.
- logging option
I set the logging option to 'False', but logs still show.
I think that the condition to set 'stderr' seems wrong.
- [ x ] I have read the [PR Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/PR/#submitting-pull-requestpr-guidelines).
- [ x ] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest).
- [ x ] I have updated …
> I found two bugs in StreamGear #287

- .gitignore
- README.md
- docs/gears/netgear/advanced/bidirectional_mode.md
- docs/gears/netgear/advanced/compression.md
- docs/gears/netgear/advanced/multi_client.md
- docs/index.md
- vidgear/gears/streamgear.py
- vidgear/gears/writegear.py
This PR fixes critical logging parameter bug which outputs debug logs even when `logging=False` in StreamGear's Real-time Mode.
#289 
There's a hidden bug in StreamGear which incorrectly infers `-video_source` attribute of `stream_params` dictionary parameter as empty when a Zero(0) index camera device is used as input, and even if `logging=False` StreamGear API outputs debug logs. This PR fixes that bug.
> 🐛 StreamGear : Fixed critical logging parameter bug. 

- docs/help/netgear_faqs.md
Added a section to the FAQ detailing a possible error if a user uses the server IP in the example code.
Based on https://github.com/abhiTronix/vidgear/issues/291 where I did not properly parse the instructions, I
(https://github.com/abhiTronix/vidgear/issues/291)
Clarifies the potential problems a user may face if they assume servers are the ones that define the IP used.
None of the above, this is just a documentation fix...
> Add "How to solve zmq.error.ZMQError" to FAQ

- vidgear/gears/streamgear.py
- vidgear/gears/writegear.py
- vidgear/tests/videocapture_tests/test_camgear.py
Removed threshold of `-input_framerate`
Fixes #306
> Fixes #306

- vidgear/gears/camgear.py
Just continuing the loop when stream protocol is of http_dash_segments.
`                
if stream_protocol == 'http_dash_segments':
continue
`
I was working on reading frames from youtube when the source URL sometimes failed so I checked, and found that when it failed was solely due to the URL was not supported by OpenCV so resolved that by just continuing the loop in case of HTTP DASH Segments Video
> SS: Dash Segments Videos are not supported by OpenCV VideoCapture.

- .github/workflows/ci_linux.yml
- setup.py
- vidgear/gears/asyncio/helper.py
- vidgear/gears/asyncio/netgear_async.py
- vidgear/gears/asyncio/webgear.py
- vidgear/gears/asyncio/webgear_rtc.py
- vidgear/gears/camgear.py
- vidgear/gears/helper.py
- vidgear/gears/netgear.py
- vidgear/gears/pigear.py
- vidgear/gears/screengear.py
- vidgear/gears/stabilizer.py
- vidgear/gears/streamgear.py
- vidgear/gears/videogear.py
- vidgear/gears/writegear.py
- vidgear/tests/writer_tests/test_non_compression_mode.py
This PR will add functionality to log current vidgear version once only when vidgear APIs are called, not at import. Less clutter in logs.
#338 
#340
This PR is aimed at reducing unnecessary logging of vidgear current version on importing its APIs. With this PR, user can now completely turn off logging and  moreover APIs with logging turned on (`logging=True`) will automatically log version only once when called within code, thus serving both purposes.
> 🧑‍💻 Maintenance: Log current vidgear version when vidgear APIs are called, not at import. (Fixes #338)

- docs/gears/webgear/overview.md
- docs/gears/webgear/params.md
- setup.py
- vidgear/gears/__init__.py
- vidgear/gears/asyncio/webgear.py
- vidgear/gears/asyncio/webgear_rtc.py
- vidgear/gears/helper.py
- vidgear/tests/streamer_tests/asyncio_tests/test_webgear.py
This PR will add feature to completely disable Data-Files Auto-Generation WorkFlow in WebGear API.
#339
This PR will add new `skip_generate_webdata` boolean optional attribute(`False` by default) to completely disable Data-Files Auto-Generation WorkFlow in WebGear API, that will only enables `/video` route by default. This feature will also implement JSONResponse as placeholder response instead of Index, 404 and 500 HTML pages, when workflow is disabled. (Note: Index HTML page will also throw 404 status code.)
> ⚡️ WebGear: Added way to completely disable Data-Files Auto-Generation WorkFlow. (Fixes #339)

- README.md
- docs/gears/webgear/params.md
- docs/overrides/assets/javascripts/extra.js
- docs/overrides/assets/stylesheets/custom.css
- docs/overrides/main.html
- mkdocs.yml
- scripts/bash/install_opencv.sh
- scripts/bash/prepare_dataset.sh
- vidgear/gears/asyncio/helper.py
- vidgear/gears/helper.py
- vidgear/tests/streamer_tests/test_streamgear_modes.py
- vidgear/tests/videocapture_tests/test_videogear.py
This PR will bring more robust implementation of `validate_audio` method with improved and more robust regex patterns for identifying audio bitrate in any audio file. Plus it will move/clone all assets from GitHub to GitLab.
#343
#347
This PR is aimed at improving regex patterns for identifying audio bitrate in any audio file and also moving/cloning all vidgear assets from GitHub to GitLab for smoother user-experience while accessing these assets.
> ⚡️Helper: Added more robust implementation of `validate_audio` method.

- README.md
- docs/bonus/TQM.md
- docs/gears.md
- docs/gears/screengear/overview.md
- docs/gears/screengear/params.md
- docs/gears/screengear/usage.md
- docs/gears/streamgear/rtfm/usage.md
- docs/gears/streamgear/ssm/usage.md
- docs/help/screengear_faqs.md
- docs/index.md
- docs/installation/pip_install.md
- setup.py
- vidgear/gears/asyncio/helper.py
- vidgear/gears/screengear.py
- vidgear/tests/network_tests/asyncio_tests/test_helper.py
- vidgear/tests/streamer_tests/test_IO_rtf.py
- vidgear/tests/streamer_tests/test_streamgear_modes.py
- vidgear/tests/videocapture_tests/test_pigear.py
- vidgear/tests/videocapture_tests/test_screengear.py
- vidgear/tests/writer_tests/test_compression_mode.py
This PR will implement `dxcam` backend support in ScreenGear API for Windows machines.
#316
#359 
This PR aimed at supporting [DXcam](https://github.com/ra1nty/DXcam) backend so that framerate can be greatly improved on Windows machine. This PR will also remove Threaded Queue mode for ScreenGear API.
> ScreenGear: Added support for DXcam backend on Windows (Fixes #316)

- .github/workflows/ci_linux.yml
- appveyor.yml
- azure-pipelines.yml
- docs/gears/netgear/params.md
- docs/gears/netgear/usage.md
- docs/gears/pigear/usage.md
- docs/gears/streamgear/params.md
- docs/gears/streamgear/rtfm/usage.md
- docs/gears/streamgear/ssm/usage.md
- docs/help/screengear_ex.md
- vidgear/gears/__init__.py
- vidgear/gears/asyncio/webgear_rtc.py
- vidgear/gears/camgear.py
- vidgear/gears/helper.py
- vidgear/gears/netgear.py
- vidgear/gears/pigear.py
- vidgear/gears/screengear.py
- vidgear/gears/stabilizer.py
- vidgear/gears/streamgear.py
- vidgear/gears/videogear.py
- vidgear/gears/writegear.py
- vidgear/tests/network_tests/asyncio_tests/test_netgear_async.py
- vidgear/tests/network_tests/test_netgear.py
- vidgear/tests/streamer_tests/asyncio_tests/test_webgear.py
- vidgear/tests/streamer_tests/asyncio_tests/test_webgear_rtc.py
- vidgear/tests/streamer_tests/test_streamgear_modes.py
- vidgear/tests/test_helper.py
This PR encompasses a series of enhancements and bug fixes across multiple components of the project, aimed at improving functionality, optimizing performance, and enhancing user experience. 
Here are the main changes included:
- Optimized peer connection closure to avoid redundant closures.
- Reduced unnecessary logging by only logging ICE connection state changes when they are not in a "failed" state.
- Enhanced stream copy support in Single Source mode (Fixes #396)
- Ignored stream copy parameter in Real-time Frames Mode or Custom Streams with appropriate warnings.
- Updated `-acodec` handling:
- Default to `aac` for Custom Streams.
- Use stream copy (`-acodec copy`) for input video’s audio when Custom Streams are disabled.
- Refined `-livestream` parameter usage to Real-time Frames …
> Core: Minor Bug Fixes 

- .github/workflows/ci_linux.yml
- azure-pipelines.yml
- vidgear/gears/asyncio/helper.py
- vidgear/gears/asyncio/netgear_async.py
- vidgear/gears/asyncio/webgear.py
- vidgear/gears/asyncio/webgear_rtc.py
- vidgear/gears/camgear.py
- vidgear/gears/helper.py
- vidgear/gears/netgear.py
- vidgear/gears/pigear.py
- vidgear/gears/screengear.py
- vidgear/gears/stabilizer.py
- vidgear/gears/streamgear.py
- vidgear/gears/videogear.py
- vidgear/gears/writegear.py
Added type annotations to improve code clarity and enable static type checking.
https://github.com/abhiTronix/vidgear/issues/376
This change addresses issue #376 by adding type annotations.
None
> Added type annotations #376
