- vidgear/gears/pigear.py
This PR solves the two major bugs in **PiGear** Class. These are as follows:
plus, I added some additional warning if source **Pi Camera Module** is not working.
> PiGear: Major Bugs HotFix 

- setup.py
- vidgear/gears/camgear.py
- vidgear/gears/helper.py
- vidgear/gears/pigear.py
- vidgear/gears/writegear.py
- Windows Cross-Platform fix (replaced `os` with `platform`)
- Windows wrong FFmpeg binaries extraction folder fixed.
- fixed wrong various variable definitions.
- Added new `framerate` class variable for CamGear class to retrieve input video's framerate.  See its usage [here](https://github.com/abhiTronix/vidgear/wiki/Compression-Mode:-FFmpeg#3-writegearcompression-mode-set-input-framerate)
- Added new [`-input_framerate`](https://github.com/abhiTronix/vidgear/wiki/Compression-Mode:-FFmpeg#2-supported-encoders-and-parameters) special parameter to WriteGear class to change/control output constant framerate in compression mode only. See its usage [here](https://github.com/abhiTronix/vidgear/wiki/Compression-Mode:-FFmpeg#3-writegearcompression-mode-set-input-framerate)
- Added `youtube-dl` …
> Major Bugs Patch and enhancements:

- .github/FUNDING.yml
- README.md
- changelog.md
This PR is about creating new **Sponsor Button**(`FUNDING.yml`) for easy contribution to VidGear development.
> Enhancement: Sponsor Button

- README.md
- changelog.md
- scripts/bash/install_opencv.sh
- scripts/bash/prepare_dataset.sh
- vidgear/gears/camgear.py
- vidgear/gears/helper.py
- vidgear/gears/netgear.py
- vidgear/gears/pigear.py
- vidgear/gears/screengear.py
- vidgear/gears/writegear.py
- vidgear/tests/benchmark_tests/test_benchmark_Videocapture.py
- vidgear/tests/benchmark_tests/test_benchmark_Videowriter.py
- vidgear/tests/benchmark_tests/test_benchmark_playback.py
- vidgear/tests/test_helper.py
- vidgear/tests/videocapture_tests/test_camgear.py
- vidgear/tests/writer_tests/test_compression_mode.py
- vidgear/tests/writer_tests/test_non_compression_mode.py
General  Code Maintenance & Enhancements.
- Updated bash script path to download test dataset in `$TMPDIR` rather than `$HOME` directory.
- Updated Code Readability.
- Updated ReadMe & Changelog with the latest changes.
- Updated Wiki Docs.
- Fixed code definitions & Typos.
Non-applicable(direct fix)
This PR aims at providing Good Code Readablilty & a secure environment for vidgear operations.
None
> [Enhancements] Code Maintenance & Enhancements

- vidgear/gears/pigear.py
This PR is a workaround for the Robust and Improved Safe Handling of any PiCamera stream related to API failures, plus an addition where PiGear will now raise RuntimeError Exception for these kinds of failures.
#61 
This PR attempts to solve the rare undetected Picamera API failures that make PiGear unable to work properly. These errors show up when a hardware failure or kernel freeze occurs due to a lack of memory/resources within Pi or maybe an internal unknown error that PiGear is unaware of.
None
> PiGear: Bugfixes for #61

- vidgear/gears/pigear.py
Major updates for PiGear API, targetting better error handling and added new functionality.
- added new `camera_num` to support multiple Picameras(#64)
- moved thread exceptions to the main thread and then re-raised(#61)
- replaced `traceback` with `sys.exc_info`. 
- added new threaded internal timing function to handle any hardware failures/frozen threads(#61)
- PiGear will not exit safely with `SystemError` if Picamera ribbon cable is pulled out to save resources.
- added support for new user-defined `HWFAILURE_TIMEOUT` options attribute to alter timeout.
- Minor tweaks for more robust overall error handling.
#61 
#64 
This PR will add more stability to PiGear API that helps in robust overall error handling and hardware failures. In addition to this, PR also introduces the `camera_num` …
> Major Updates and BugFixes for PiGear

- scripts/bash/install_opencv.sh
- scripts/bash/prepare_dataset.sh
- vidgear/gears/netgear.py
Major bugfixes for NetGear API, targetting better performance, smoother playback and robust error handling and added new exclusive feature updates.
- **Updates:**
- Introducing exclusive Bi-Directional Mode for bidirectional data transmission(#75)
- Added new `return_data` parameter to `recv()` function.
- Added new `bidirectional_mode` attribute for enabling this mode.
- Added support for `PAIR` & `REQ/REP` patterns for this mode
- Added support for sending data of any python datatype.
- Added support for `message` parameter for non-exclusive primary modes for this mode
- Added support for `REQ/REP` pattern in Multi-Server Mode
- Added `force_terminate` attribute flag for handling force socket termination at the server if there's latency in the network. This enables easy server-side …
> Major Updates and Bugfixes for NetGear API

- README.md
- vidgear/gears/camgear.py
- vidgear/gears/helper.py
- vidgear/gears/netgear.py
- vidgear/gears/pigear.py
- vidgear/gears/screengear.py
- vidgear/gears/stabilizer.py
- vidgear/gears/videogear.py
- vidgear/gears/writegear.py
- vidgear/tests/test_helper.py
Adding Data encapsulation for Videgear APIs.
- Implemented encapsulation for class functions and variables on all gears
- Updated README readability
- Minor fixes
#83 
This PR will add encapsulation to vidgear's python code. This will provide hidden private functions and variable features to current API for more robust and error-free performance.
Encapsulation is the packing of data and functions operating on that data into a single component and restricting the access to some of the object’s components. Encapsulation means that the internal representation of an object is generally hidden from view outside of the object’s definition. 
Python drops that pretense of security and encourages programmers to be responsible. In practice, this works very nicely. If we want to emulate private …
> Code Encapsulation & Updates:

- README.md
- codecov.yml
- vidgear/gears/camgear.py
- vidgear/gears/helper.py
- vidgear/gears/netgear.py
- vidgear/gears/pigear.py
- vidgear/gears/screengear.py
- vidgear/gears/stabilizer.py
- vidgear/gears/videogear.py
- vidgear/gears/writegear.py
- vidgear/tests/benchmark_tests/test_benchmark_Videocapture.py
- vidgear/tests/benchmark_tests/test_benchmark_Videowriter.py
- vidgear/tests/benchmark_tests/test_benchmark_playback.py
- vidgear/tests/network_tests/test_netgear.py
- vidgear/tests/test_helper.py
- vidgear/tests/videocapture_tests/test_camgear.py
- vidgear/tests/videocapture_tests/test_screengear.py
- vidgear/tests/videocapture_tests/test_videogear.py
- vidgear/tests/writer_tests/test_compression_mode.py
- vidgear/tests/writer_tests/test_non_compression_mode.py
This PR brings various logging updates to fix faulty behavior that can conflict with other python libraries.
- Added new `logging handler` helper function.
- Removed conflicting system-wide dictionary logging formatter.
- Isolated each API & test loggers and defined them globally to avoid redundant clones.
- Removed PiGear from CLI completely due to camera hardware emulation limitation.
- Fixed incorrect logic for pulling frames in ScreenGear CLI test
- Limited imported OpenCV API version check scope to `helper.py` only.
- Other Minor fixes.
None(direct fix)
The vidgear's custom color-logger can conflict with other libraries that breaks functionality. Similar behavior was encounter when `vidgear` is used with `uvicorn` python library(More info: …
> Code Maintenance: Logging Updates

- .travis.yml
- README.md
- appveyor.yml
- changelog.md
- codecov.yml
- scripts/bash/prepare_dataset.sh
- setup.py
- vidgear/gears/__init__.py
- vidgear/gears/__main__.py
- vidgear/gears/helper.py
- vidgear/gears/pigear.py
- vidgear/gears/stabilizer.py
- vidgear/gears/videogear.py
- vidgear/gears/webgear.py
- vidgear/tests/benchmark_tests/test_benchmark_Videowriter.py
- vidgear/tests/network_tests/test_netgear.py
- vidgear/tests/network_tests/test_webgear.py
- vidgear/tests/test_helper.py
- vidgear/tests/videocapture_tests/test_camgear.py
- vidgear/tests/videocapture_tests/test_videogear.py
_WebGear is a powerful [ASGI](https://asgi.readthedocs.io/en/latest/) Video-streamer API, that is built upon [Starlette](https://www.starlette.io/) - a lightweight ASGI framework/toolkit, which is ideal for building high-performance asyncio services._ 
WebGear API **provides a flexible but robust asyncio wrapper around [Starlette](https://www.starlette.io/) ASGI application and can easily access its various components For a long time, vidgear lacks the ability to stream video to web browsers. Our goal through this proposal is to test whether it is possible to stream video frames over Starlette in real-time independently.** Thereby providing it the ability to interact with the Starlette's ecosystem of shared middleware and mountable applications & seamless access to its various [Response …
> Enhancement:  Introducing WebGear - A powerful ASGI Video-streamer API

- README.md
- changelog.md
- vidgear/gears/__main__.py
- vidgear/gears/camgear.py
- vidgear/gears/helper.py
- vidgear/gears/netgear.py
- vidgear/gears/pigear.py
- vidgear/gears/screengear.py
- vidgear/gears/videogear.py
- vidgear/gears/webgear.py
- vidgear/gears/writegear.py
- vidgear/tests/benchmark_tests/test_benchmark_Videowriter.py
- vidgear/tests/network_tests/test_netgear.py
- vidgear/tests/network_tests/test_webgear.py
- vidgear/tests/test_helper.py
- vidgear/tests/videocapture_tests/test_camgear.py
- vidgear/tests/videocapture_tests/test_screengear.py
- vidgear/tests/videocapture_tests/test_videogear.py
- vidgear/tests/writer_tests/test_IO.py
- vidgear/tests/writer_tests/test_compression_mode.py
- vidgear/tests/writer_tests/test_non_compression_mode.py
CLI Maintenance updates and related bugfixes.
- Re-implemented and simplified all CLI tests with maximum code-coverage in mind.
- Added new `mkdir_safe` helper function for creating directories safely.
- Added new gif for WebGear API.
- Removed redundant CLI tests for APIs.
- Removed several redundant `try-catch` loops.
- Renamed `youtube_url_validation` as `youtube_url_validator`.
- Several minor wrong/duplicate variable definitions and various bugs fixed.
- Improved and expanded logging.
- Updated docs.
None _(direct fix)_
This PR is aimed at re-implementing and simplifying CLI tests with maximum code-coverage in mind and solving related bugs wherever encountered.
None
> CLI Maintenance Updates and bugfixes

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/PULL_REQUEST_TEMPLATE.md
- docs/gears/writegear/compression/params.md
- vidgear/gears/asyncio/helper.py
- vidgear/gears/asyncio/netgear_async.py
- vidgear/gears/asyncio/webgear.py
- vidgear/gears/camgear.py
- vidgear/gears/helper.py
- vidgear/gears/netgear.py
- vidgear/gears/pigear.py
- vidgear/gears/screengear.py
- vidgear/gears/stabilizer.py
- vidgear/gears/videogear.py
- vidgear/gears/writegear.py
- vidgear/tests/benchmark_tests/test_benchmark_network.py
- vidgear/tests/benchmark_tests/test_benchmark_playback.py
- vidgear/tests/network_tests/asyncio_tests/test_helper.py
- vidgear/tests/network_tests/asyncio_tests/test_netgear_async.py
- vidgear/tests/network_tests/asyncio_tests/test_webgear.py
- vidgear/tests/network_tests/test_netgear.py
- vidgear/tests/test_helper.py
- vidgear/tests/videocapture_tests/test_camgear.py
- vidgear/tests/videocapture_tests/test_screengear.py
- vidgear/tests/videocapture_tests/test_videogear.py
- vidgear/tests/writer_tests/test_IO.py
- vidgear/tests/writer_tests/test_compression_mode.py
- vidgear/tests/writer_tests/test_non_compression_mode.py
This PR will add support for Non-File FFMPEG output URLs to WriteGear's Compression Mode, which will facilitates effortless network streaming within its API.
Enhancements:
- Added support for automatic handling for non path/file outputs in compression modes only.
- Implemented new `is_valid_url` method in Helper to cross-check non-file urls.
- WriteGear will now automatically checks if given url has scheme/protocol supported by assigned ffmpeg for compression mode only.
- If validated, WriteGear will use given URL to stream frames to network.
- Improved check for valid system path detection for WriteGear outputs.
- **Note:** This feature is only available with WriteGear's Compression Mode.
- :warning: WriteGear will throw ValueError if scheme/protocol is not supported by assigned FFmpeg. …
> WriteGear API: Support for Non-File FFMPEG URL outputs

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/config.yml
- README.md
- docs/bonus/TQM.md
- docs/changelog.md
- docs/contribution.md
- docs/gears.md
- docs/gears/camgear/params.md
- docs/gears/camgear/usage.md
- docs/gears/pigear/usage.md
- docs/gears/streamgear/introduction.md
- docs/gears/streamgear/rtfm/overview.md
- docs/gears/webgear/usage.md
- docs/gears/webgear_rtc/advanced.md
- docs/gears/webgear_rtc/usage.md
- docs/gears/writegear/compression/advanced/cciw.md
- docs/gears/writegear/compression/usage.md
- docs/help/camgear_faqs.md
- docs/help/general_faqs.md
- docs/index.md
- docs/installation/pip_install.md
- docs/switch_from_cv.md
- mkdocs.yml
- setup.py
- vidgear/gears/asyncio/webgear_rtc.py
- vidgear/tests/streamer_tests/asyncio_tests/test_webgear_rtc.py
Fixed WebGear_RTC bug that leads to stream freeze on reloading. 
- Implemented new algorithm to continue stream even when webpage is reloaded.
- Inherit and modified `next_timestamp` VideoStreamTrack method for generating accurate timestamps.
- Implemented `reset_connections` callable to reset all peer connections and recreate Video-Server timestamps. (Implemented by @kpetrykin)
- Added `close_connection` endpoint in JavaScript to inform server page refreshing.(Thanks to @kpetrykin)
- Added exclusive reset connection node `/close_connection` in routes.
- Added `reset()` method to Video-Server class for manually resetting timestamp clock.
- Added `reset_enabled` flag to keep check on reloads.
- Fixed premature webpage auto-reloading.
- Added additional imports.
- Fixed code typos and …
> WebGear_RTC: Fixed stream freezes after web-page reloading

- README.md
- docs/contribution/PR.md
- docs/gears.md
- docs/gears/netgear/advanced/bidirectional_mode.md
- docs/gears/netgear/advanced/compression.md
- docs/gears/netgear/advanced/ssh_tunnel.md
- docs/gears/webgear/advanced.md
- docs/gears/webgear/params.md
- docs/gears/webgear/usage.md
- docs/gears/webgear_rtc/params.md
- docs/help.md
- docs/help/stabilizer_faqs.md
- docs/index.md
- docs/installation/pip_install.md
- docs/installation/source_install.md
- docs/switch_from_cv.md
- mkdocs.yml
- vidgear/gears/asyncio/helper.py
- vidgear/gears/asyncio/webgear.py
- vidgear/gears/asyncio/webgear_rtc.py
- vidgear/gears/helper.py
- vidgear/gears/stabilizer.py
- vidgear/tests/network_tests/asyncio_tests/test_helper.py
- vidgear/tests/streamer_tests/asyncio_tests/test_webgear.py
- vidgear/tests/test_helper.py
This PR will track `simplejpeg` integration into WebGear to replace OpenCV's JPEG encoding/decoding.
#202 
OpenCV is currently throttling performance in WebGear, that depends on OpenCV JPEG encoding specifically for frame-compression. Therefore we are planning to move to new `simplejpeg` library that offers some extreme performance improvements over OpenCV, and includes really favorable features like:
- Read and write directly from/to memory.
- Uses Cython's plain C performance layer above underlying [`libjpegturbo`](https://github.com/libjpeg-turbo/libjpeg-turbo) compression  library, therefore extremely faster than others.
- Compatible with numpy arrays.
- standalone.
None
> ⚡️ WebGear: Updated JPEG Frame compression with simplejpeg

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/proposal.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
- docs/gears/netgear/advanced/bidirectional_mode.md
- docs/gears/netgear/advanced/multi_client.md
- docs/gears/netgear/advanced/multi_server.md
- docs/help/netgear_faqs.md
- vidgear/gears/netgear.py
- vidgear/tests/network_tests/test_netgear.py
Implemented bidirectional data transfer support by extending Bidirectional mode support to existing NetGear's exclusive Multi-Clients and Multi-Servers modes.
#278 
#282 
Currently both [Multi-Clients](https://abhitronix.github.io/vidgear/latest/gears/netgear/advanced/multi_client/) and [Multi-Servers](https://abhitronix.github.io/vidgear/latest/gears/netgear/advanced/multi_server/) exclusive modes only supports Unidirectional data transfer since [they're incompatible with NetGear's Bidirectional Mode(disables it automatically)](https://abhitronix.github.io/vidgear/latest/help/netgear_faqs/#what-exclusive-modes-are-compatible-with-each-other-in-netgear-api). This PR is implementing bidirectional data transfer support by extending Bidirectional mode support to existing Multi-Client and …
> 🚧 NetGear: Bidirectional data transfer support to Multi-Clients and Multi-Servers mode.

- docs/help/netgear_ex.md
I made 3 changes: (1) added a missing import (2) removed `self.` typo (3) removed the return value in the async as it triggers an error.
#294 
Small tweak to the bonus example code.
None of the above, its a small doc fix
> Fix some example code issues

- .github/workflows/ci_linux.yml
- README.md
- appveyor.yml
- azure-pipelines.yml
- docs/gears/netgear_async/usage.md
- docs/gears/pigear/usage.md
- docs/gears/screengear/usage.md
- docs/gears/stabilizer/usage.md
- docs/gears/writegear/compression/advanced/cciw.md
- docs/gears/writegear/compression/params.md
- docs/gears/writegear/compression/usage.md
- docs/gears/writegear/non_compression/params.md
- docs/gears/writegear/non_compression/usage.md
- docs/help/screengear_ex.md
- docs/help/stabilizer_ex.md
- docs/help/videogear_ex.md
- docs/help/writegear_ex.md
- docs/switch_from_cv.md
- scripts/bash/install_opencv.sh
- vidgear/gears/helper.py
- vidgear/gears/streamgear.py
- vidgear/gears/writegear.py
- vidgear/tests/videocapture_tests/test_camgear.py
- vidgear/tests/writer_tests/test_compression_mode.py
- vidgear/tests/writer_tests/test_non_compression_mode.py
This PR will allow users to define any thinkable pixel-format _(supported by installed FFmpeg)_ thereby providing them with full control of the incoming frames bit depth.
#332
#333 
#309
This PR is aimed at supporting both user-defined and higher than 8-bit depth input frames pixel-formats and adding some other important changes such as support for Context Managers.
> ✨ WriteGear: Added support for user-defined and higher than 8-bit depth input frames pixel-format. (Fixes #332)

- README.md
- docs/gears/screengear/usage.md
- docs/gears/webgear/overview.md
- docs/gears/webgear/params.md
- docs/index.md
- docs/installation/pip_install.md
- vidgear/gears/asyncio/webgear.py
- vidgear/gears/asyncio/webgear_rtc.py
- vidgear/gears/screengear.py
- vidgear/tests/streamer_tests/asyncio_tests/test_webgear.py
- vidgear/tests/streamer_tests/asyncio_tests/test_webgear_rtc.py
These PR include various improvements and fixes for asyncio packages namely Webgear and WebGear_RTC.
#360 
#362
This PR introduce bug fix related to  `ndim==3` grayscale frames in Webgear_RTC API, and added option to add custom video endpoint path to Webgear API, and other minor fixes.
> Asyncio: minor improvements and bugfixes.

- .github/FUNDING.yml
- .github/workflows/ci_linux.yml
- .github/workflows/deploy_docs.yml
- appveyor.yml
- azure-pipelines.yml
- docs/installation.md
- docs/installation/pip_install.md
- docs/installation/source_install.md
- setup.py
- vidgear/gears/asyncio/webgear.py
- vidgear/gears/asyncio/webgear_rtc.py
- vidgear/tests/streamer_tests/asyncio_tests/test_webgear_rtc.py
This PR will drop support for 3.7.x legacy which will no longer be supported in the upcoming version `v0.3.2` of vidgear. Also, support for new python 3.11.x legacy will also be officially added.
#369
As of 05 Jun 2023, [Python 3.7.x legacy has reached its end of support](https://endoflife.date/python), resulting in the discontinuation of security updates and general widespread availability. Consequently, this PR will drop support for 3.7.x legacy will no longer be supported in the upcoming version `v0.3.2` of vidgear. Also, support for new python 3.11.x legacy will also be officially added in this same version, by updating CI workflows on  all environments.
> 🏗️ Maintenance: Replacing python 3.7 legacy support with 3.11 legacy.

- vidgear/gears/writegear.py
In this pull request, I've added a new feature to enable detached subprocess creation on Windows within the `writegear` module. This enhancement enhances the process management capabilities of the module.
This can be useful while creating an exe file for a python script that uses writegear. On windows even after creating the exe file in windowed mode or no-console mode, the ffmpeg.exe command line window would pop up while its being used by write gear.
> Writegear ffmpeg creationflag
